config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :users, only: [:index,:show]
  resources :questions, only: [:index, :new,:create,:destroy] do
    resources :answers, only: [:index,:create,:destroy] do
      resource :likes, only: [:create, :destroy]
    end  
  end  
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :answer,presence: true, length: { maximum: 72 }
  
  belongs_to :user 
  belongs_to :question
  has_many :likes, dependent: :destroy
  has_many :liked_users, dependent: :destroy,through: :likes, source: :user
  
  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question,presence: true, length: { maximum: 80 }
  
  belongs_to :user
  has_one_attached :image
  has_many  :answers , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :nickname,presence: true, length: { maximum: 10 }     
  validates :profile,presence: true,length: { maximum: 100 }
  
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_answers, dependent: :destroy, through: :likes, source: :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:index,:create]
  
  def index
    if params[:like_count]
      answers = @question.answers.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
      @answers = Kaminari.paginate_array(answers).page(params[:page]).per(5)
    else
      @answers = @question.answers.page(params[:page]).per(5).order(created_at: :desc)
    end  
    @answer = Answer.new
  end
 
  def create
    @answers = @question.answers.order(created_at: :desc)
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to  question_answers_path
    else
      redirect_back(fallback_location: root_path)
    end      
  end
 
  def destroy
    answer = Answer.find(params[:id])
    if answer.user_id == current_user.id
      answer.destroy
      redirect_back(fallback_location: root_path)
    end  
  end
 
 private
  def answer_params
    params.require(:answer).permit(:answer).merge(user_id: current_user.id,question_id: params[:question_id])
  end
  
  def set_question
    @question = Question.find(params[:question_id])
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:profile])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_answer, only: [:create,:destroy]
  
  def create
    like = current_user.likes.new(answer_id: @answer.id)
    like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = current_user.likes.find_by(answer_id: @answer.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def set_answer
    @answer = Answer.find(params[:answer_id])
  end 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    if params[:answer_count]
      questions = Question.includes(:answers).sort {|a,b| b.answers.size <=> a.answers.size}
      @questions = Kaminari.paginate_array(questions).page(params[:page]).per(9)
    else
      @questions = Question.page(params[:page]).per(9).order(created_at: :desc)
    end
  end
  
  def new
    @question = Question.new
  end
  
  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def destroy
    question = Question.find(params[:id])
    if question.user_id == current_user.id
      question.destroy
      redirect_back(fallback_location: root_path)
    end  
  end  

  private
  def question_params
    params.require(:question).permit(:question,:image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:index,:show]
  
  def index
    if params[:like_average]
      answer_like_count = {}
      User.all.each do |user|
        if user.answers.present?
          answer_like_count.store(user, Like.where(answer_id: Answer.where(user_id: user.id).pluck(:id)).count/user.answers.count.to_f)
        end
      end
      @user_answer_like_ranks = answer_like_count.sort_by { |_, v| v }.reverse.to_h.keys
    else 
      answer_like_count = {}
      User.all.each do |user|
        answer_like_count.store(user, Like.where(answer_id: Answer.where(user_id: user.id).pluck(:id)).count)
      end
      @user_answer_like_ranks = answer_like_count.sort_by { |_, v| v }.reverse.to_h.keys
    end
  end
  
  def show
    @user = User.find(params[:id])
    @user_answers = @user.answers
    @likes_count = 0
    @user_answers.each do |answer|
      @likes_count += answer.likes.count
    end
    answer_like_count = {}
    User.all.each do |user|
      answer_like_count.store(user, Like.where(answer_id: Answer.where(user_id: user.id).pluck(:id)).count)
    end
    @user_answer_like_ranks = answer_like_count.sort_by { |_, v| v }.reverse.to_h.keys
  end
  
  private
  def set_user
    @users = User.all
  end 
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/index.html.erb
<div class="index_main">
  <%= link_to '< 前のページへ戻る',:back, class: "redirect_back" %>
  <%= link_to '<< トップページへ戻る',root_path, class: "redirect" %>
  <div class="inner">
    <ul class="question_lists_answer">
      <div class="question_list_answer">
        <div class="question_answer">
         <%= link_to @question.user.nickname,user_path(@question.user.id),class: :q %>さんのお題
        </div>
        <% if @question.image.present? %>
         <%= image_tag @question.image, class: "item-img" %>
        <% end %>
        <div class="question"><%= @question.question %></div>
        <% if user_signed_in? %>
          <%= form_with model: [@question,@answer],local: true do |f|%>
            <div class="field_answer">
              <%= f.text_area :answer,maxlength:"72", rows:"3",cols:"39",placeholder: "スペース含む最大72文字,3行まで" %>
            </div>
            <div class="actions_answer">
              <%= f.submit "回答する", class: :form__btn__answer %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="answer_index">
        <% if params[:like_count] %>
         回答一覧：<%= link_to 'ランキング',question_answers_path(like_count:"true")%>
                 <%= link_to '新着順', question_answers_path,class: "new_questions"%>       
        <% else %>
         回答一覧：<%= link_to '新着順',question_answers_path %>
                 <%= link_to 'ランキング',question_answers_path(like_count:"true"),class: "new_questions" %>
        <% end %>
        <div class="page"><%= paginate @answers %></div>
      </div>
      <div class="answer_lists">
        <% num=0 %>
          <% @answers.each do |answer| %>
            <div class="answer_list">
              <% if params[:page] %>
                <% num+=1 %>
                <% unless params[:like_count] %>
                  <div class="answers_num"><%= (num-5) + params[:page].to_i * 5 %>.</div>
                <% else %>
                  <div class="answers_num"><%= (num-5) + params[:page].to_i * 5 %>位</div>
                <% end %>
              <% else %> 
                <% unless params[:like_count] %>
                  <div class="answers_num"><%= num+=1 %>.</div>
                <% else %>
                  <div class="answers_num"><%= num+=1 %>位</div>
                <% end %>
              <% end %> 
              <% if user_signed_in? && current_user.id == answer.user_id %>
                <%= link_to '削除', "/questions/#{@question.id}/answers/#{answer.id}", method: :delete,class: :answer_delete %>
              <% end %>
              <div class="answer_name"><%= link_to answer.user.nickname,user_path(answer.user.id),class: :answer_name_q %>さん</div>
              <div class="answer_answer"><%= answer.answer %></div>
              <% if answer.liked_by?(current_user) %>
                <%= link_to  "/questions/#{@question.id}/answers/#{answer.id}/likes",class: "likes", method: :delete do %>
                  <div class="heart"><%= "🧡" %><% end %><%= " × #{(answer.likes.count)}" %></div>
              <% else %>
                <%= link_to "/questions/#{@question.id}/answers/#{answer.id}/likes",class: "likes", method: :post do %>
                  <div class="heart"><%= "🤍" %><% end %><%= " × #{(answer.likes.count)}" %></div>
              <% end %>
            </div>
          <% end %> 
      </div> 
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ogiri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="title"><%= link_to "大喜利掲示板",root_path %></div>
            <% if user_signed_in? %>
              <div class="ranks"><%= link_to "ユーザーランキング",users_path %></div>
            <% else %>
              <div class="ra">お題に回答するにはユーザー登録をしよう！！</div> 
            <% end %>
            <% if user_signed_in? %>
              <div class="greeting">
                おいでやす<%= link_to "#{current_user.nickname}",user_path(current_user.id),class: :greeting__link%>さん🙇
              </div> 
              <div class="nav__right"> 
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: :nav__btn %>
                <%= link_to "お題投稿", new_question_path, class: :nav__btn %>
              </div> 
            <% else %>
              <div class="nav__right">
                <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
                <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
              </div>
            <% end %>
          </div>
    </header>
      <%= yield %>
   <footer class="footer">
      <p class="copyright">Copyright © OGIRI KEIJIBAN All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/questions/_questions.html.erb
<ul class="question_lists">
  <% num=0 %>
    <% @questions.each do |question| %>
      <div class="question_list">
        <% if params[:page] %>
          <% num+=1 %>
          <div class="num"><%=(num-9) + params[:page].to_i * 9 %>.</div>
        <% else %>
          <div class="num"><%= num+=1 %>.</div>
        <% end %>
        <% if user_signed_in? && current_user.id == question.user_id %>
          <%= link_to '削除', question_path(question.id), method: :delete,class: :question_delete %>
        <% end %>
        <div class="question_answer">
          <%= link_to question.user.nickname,user_path(question.user.id),class: :q %>さんのお題
        </div>
        <% if question.image.present? %>※画像付き※
          <div class="question_image"><%= question.question %></div>
        <% else %>
          <div class="question"><%= question.question %></div>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to "回答ページへ", question_answers_path(question.id),class: :answer_page %>
        <% end %>
        <div class="answer_num"><%= "回答数(#{question.answers.count})" %></div>
        </div> 
    <% end %>  
</ul>

app/views/questions/index.html.erb
<div class="index_main">
  <div class="inner">
   <div class="index">
        <% if params[:answer_count] %>
          お題一覧：<%= link_to '人気順',root_path(answer_count:"true") %> 
                <%= link_to '新着順',root_path ,class: "new_questions" %>      
        <% else %>
          お題一覧：<%= link_to '新着順',root_path %>
                <%= link_to '人気順',root_path(answer_count:"true"),class: "new_questions" %>
        <% end %>
        <div class="page"><%= paginate @questions %></div>
    </div>  
      <%= render 'questions', model: @questions %>
  </div>
</div>  

app/views/questions/new.html.erb
<div class="main">
  <%= link_to '< 前のページへ戻る',:back, class: "redirect_back" %>
  <%= link_to '<< トップページへ戻る',root_path, class: "redirect" %>
  <%= form_with model: @question, local: true do |f|%>
    <div class="img-upload">
      <div class="weight-bold-text">
        お題画像
      </div>
      <div class="click-upload">
          <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <div class="question_field">
      <%= f.label :question, "お題（スペース含む最大80文字,4行まで）" %><br />
      <%= f.text_area :question,maxlength:"80", rows:"4",cols:"32" %>
    </div>
    <div class="actions">
      <%= f.submit "投稿する", class: :form__btn  %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="index_main">
  <%= link_to '< 前のページへ戻る',:back, class: "redirect_back" %>
  <%= link_to '<< トップページへ戻る',root_path, class: "redirect" %>
  <div class="ranking"><%= "ユーザーランキングTOP10(#{@users.count}人中)" %></div>
    <div class="rank_index">
      <% if params[:like_average] %>
        <%= link_to '総合ランキング',users_path,class: "new_questions" %>:
        <%= link_to '平均ランキング(1回答あたり)', users_path(like_average:"true") %>       
      <% else %>
        <%= link_to '総合ランキング',users_path %>:
        <%= link_to '平均ランキング(1回答あたり)',users_path(like_average:"true"),class: "new_questions" %>
      <% end %>
    </div>
    <% if params[:like_average] %>
      <div class="rankings">
        <table border="1">
          <tr>
            <th>👑</th><th>ニックネーム</th><th>平均🧡獲得数</th>
          </tr>
            <% num = 0 %>
            <% @user_answer_like_ranks.first(10).each do |user| %>
              <% num += 1%>
                <tr>
                  <td><%= num %>位</td>
                  <td><%= link_to user.nickname,user_path(user.id),class: "rank_user" %></td>
                  <% user_answers = user.answers %>
                  <% likes_count = 0 %>
                  <% user_answers.each do |answer| %>
                    <% likes_count += answer.likes.count %>
                  <% end %>
                  <td><%= sprintf("%.2f",likes_count/user_answers.count.to_f) %></td>
                </tr>
          <% end %>
        </table>
      </div>
    <% else %>
      <div class="rankings">
        <table border="1">
          <tr>
            <th>👑</th><th>ニックネーム</th><th>合計🧡獲得数</th>
          </tr>
            <% num = 0 %>
            <% @user_answer_like_ranks.first(10).each do |user| %>
              <% num += 1%>
                <tr>
                  <td><%= num %>位</td>
                  <td><%= link_to user.nickname,user_path(user.id),class: "rank_user" %></td>
                  <% user_answers = user.answers %>
                  <% likes_count = 0 %>
                  <% user_answers.each do |answer| %>
                    <% likes_count += answer.likes.count %>
                  <% end %>
                  <td><%= likes_count %></td>
                </tr>
            <% end %>
        </table>
      </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="main">
  <%= link_to '< 前のページへ戻る',:back, class: "redirect_back" %>
  <%= link_to '<< トップページへ戻る',root_path, class: "redirect" %>
  <div class="user_box">
    <div class="profile">
      <% unless current_user.id == @user.id %>
        <%= @user.nickname %>さんのプロフィール
      <% else %>
        自分のプロフィール
      <% end %>  
    </div>
    <div class="user_name">ランキング</div>
      <% @user_answer_like_ranks.each.with_index(1) do |user, i| %>
        <% if @user == user %>
          <%= i %>位
        <% end %> 
      <% end %>
      <%= "/ #{@user_answer_like_ranks.count}人" %>
      <div class="user_profile">ひとこと</div><div class="users_profile"><%= @user.profile %></div>
      <div class="user_question">お題出題数</div><%= @user.questions.count %>
      <div class="user_answer">お題回答数</div><%= @user.answers.count %>
      <div class="user_rank">合計🧡獲得数</div><%= @likes_count %>
  </div>
</div>